#!/usr/bin/env bash

# We create a reference to the filepath, in this case Downloads.
filepath="$HOME/Downloads"

# We create a list of all folders we want to check and create.
folders="Images Music Videos PDF Documents Archives Code Other"

while true
do

# We grab each folder from folders and check if they exist, otherwise we create them.
for folder in $folders
do
    mkdir -p "$filepath/$folder"
    echo "Created $filepath/$folder"  
done


for file in "$filepath"/*
do
    if [ -f "$file" ]; then
        extension="${file##*.}"
        extension="${extension,,}"
        
        case "$extension" in
            jpg|jpeg|png|gif)
                folder="Images"
                ;;
            mp3|wav|flac)
                folder="Music"
                ;;
            mp4|mkv|avi)
                folder="Videos"
                ;;
            pdf)
                folder="PDF"
                ;;
            txt|doc|docx)
                folder="Documents"
                ;;
            zip|tar|gz|bz2|xz|7z|rar)
                folder="Archives"
                ;;
            sh|py|jc|c|cpp|java)
                folder="Code"
                ;;

            *)
                folder="Other"
                ;;
        esac
        
        echo "Moving: $file -> $filepath/$folder/"
        mv -- "$file" "$filepath/$folder/"
    fi

done

# We wait 5 secounds before starting the next while loop

sleep 5

done
