#!/usr/bin/env bash

mkdir -p "$HOME/.local/bin"
mkdir -p "$HOME/.config/systemd/user"

cp dlorg "$HOME/.local/bin/dlorg"
cp dlorg.service "$HOME/.config/systemd/user/dlorg.service"

chmod +x "$HOME/.local/bin/dlorg"

systemctl --user daemon-reload
systemctl --user enable --now dlorg.service

echo "Downloads organizer installed!"
